# Generated by Django 5.2 on 2025-10-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_developer_first_name_alter_developer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
