# Generated by Django 5.2 on 2025-10-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_developer_project_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='developer',
            new_name='developers',
        ),
    ]
